Repository osu-tournament-rating/otr-web, pull requests merged in 2024-05, with the labels that each got.

#174 Rename 'winrate' to 'winRate' everywhere
  app/actions.ts
  app/dashboard/page.tsx
  app/leaderboards/page.tsx
  app/users/[id]/page.tsx
  components/Charts/RadarChart/RadarChart.tsx
  components/Collapsible/FiltersCollapsible/FiltersCollapsible.tsx
  components/Leaderboard/UserStats/UserStats.tsx
  components/Range/RangeSlider.module.css
  lib/types.ts
Labels: size/M

#175 Profiles gets current ruleset
  app/actions.ts
  app/users/[id]/error.module.css
  app/users/[id]/error.tsx
Labels: size/L

#179 Develop
  app/actions.ts
  app/dashboard/page.tsx
  app/leaderboards/page.tsx
  app/users/[id]/error.module.css
  app/users/[id]/error.tsx
  app/users/[id]/page.tsx
  components/Charts/AreaChart/AreaChart.module.css
  components/Charts/BarChart/BarChart.module.css
  components/Charts/DoughnutChart/DoughnutChart.module.css
  components/Charts/PlayersBarChart/PlayersBarChart.module.css
  components/Charts/PlayersBarChart/PlayersBarChart.tsx
  components/Charts/RadarChart/RadarChart.module.css
  components/Charts/RadarChart/RadarChart.tsx
  components/Collapsible/FiltersCollapsible/FiltersCollapsible.tsx
  components/Dashboard/GridCard/GridCard.module.css
  components/Dashboard/GridCard/GridCard.tsx
  components/Leaderboard/UserStats/UserStats.tsx
  components/Range/RangeSlider.module.css
  lib/types.ts
Labels: size/L

#180 Staging
  app/actions.ts
  app/dashboard/page.tsx
  app/leaderboards/page.tsx
  app/users/[id]/error.module.css
  app/users/[id]/error.tsx
  app/users/[id]/page.tsx
  components/Charts/AreaChart/AreaChart.module.css
  components/Charts/BarChart/BarChart.module.css
  components/Charts/DoughnutChart/DoughnutChart.module.css
  components/Charts/PlayersBarChart/PlayersBarChart.module.css
  components/Charts/PlayersBarChart/PlayersBarChart.tsx
  components/Charts/RadarChart/RadarChart.module.css
  components/Charts/RadarChart/RadarChart.tsx
  components/Collapsible/FiltersCollapsible/FiltersCollapsible.tsx
  components/Dashboard/GridCard/GridCard.module.css
  components/Dashboard/GridCard/GridCard.tsx
  components/Leaderboard/UserStats/UserStats.tsx
  components/Range/RangeSlider.module.css
  lib/types.ts
Labels: size/L

#182 New deployment strategy
  .github/release.yml
  .github/workflows/dev-deploy.yml
  .github/workflows/prod-deploy.yml
  .github/workflows/staging-deploy.yml
Labels: size/L

#183 Change rating display/filter to use round/ceil instead of floor
  components/Collapsible/FiltersCollapsible/FiltersCollapsible.tsx
  components/Leaderboard/Leaderboard.tsx
Labels: size/XS

#184 Fix staging ref
  .github/workflows/staging-deploy.yml
Labels: size/XS

#185 Add restart always to docker run
  .github/workflows/prod-deploy.yml
  .github/workflows/staging-deploy.yml
Labels: size/XS

#189 Ruleset changes
  app/actions.ts
Labels: size/S

#190 No data skeleton for dashboard and user page
  app/actions.ts
  app/dashboard/error.tsx
  app/dashboard/page.tsx
  app/globals.css
  app/users/[id]/error.tsx
  app/users/[id]/page.tsx
  components/Dashboard/NoDataContainer/NoDataContainer.module.css
  components/Dashboard/NoDataContainer/NoDataContainer.tsx
  components/Dashboard/UserMainCard/UserMainCard.module.css
  components/Dashboard/UserMainCard/UserMainCard.tsx
  components/Profile/UserMainCard/UserMainCard.tsx
  public/logos/otr-logo-2.svg
Labels: size/XL
