Repository osu-tournament-rating/otr-web, pull requests merged in 2024-11, with the labels that each got.

#229 Add CODEOWNERS file
  .github/CODEOWNERS
Labels: size/XS

#228 Add friends.read scope to osu! authorization
  app/actions.ts
Labels: type:feature, size/XS

#224 Refactor session handling
  .env.example
  .gitignore
  app/actions.ts
  app/actions/login.ts
  app/actions/session.ts
  app/auth/route.ts
  app/submit/page.tsx
  app/unauthorized/page.tsx
  components/Button/LoginButton.tsx
  components/Leaderboard/Leaderboard.tsx
  components/NavBar/ModeSwitcher/ModeSwitcher.tsx
  components/NavBar/NavBar.tsx
  components/NavBar/Routes/Routes.tsx
  components/NavBar/UserLogged/UserLogged.tsx
  components/Tournaments/InfoContainer/InfoContainer.tsx
  components/Tournaments/Lists/TournamentsList.tsx
  lib/auth.ts
  lib/types.ts
  middleware.ts
  package-lock.json
  package.json
  util/UserLoggedContext.tsx
  util/hooks.ts
Labels: size/XL

#230 bump client package version
  app/actions/login.ts
  package-lock.json
  package.json
Labels: size/S
