Repository osu-tournament-rating/otr-web, pull requests merged in 2024-03, with the labels that each got.

#111 Implementation of new oauth api
  app/actions.ts
  app/auth/route.ts
  util/ErrorContext.tsx
Labels: size/M

#115 Develop
  app/actions.ts
  app/auth/route.ts
  util/ErrorContext.tsx
Labels: size/M

#114 Calling refresh with some status codes
  app/actions.ts
  app/auth/route.ts
  app/submit/page.tsx
  lib/types.ts
  middleware.ts
  package-lock.json
  package.json
  util/UserLoggedContext.tsx
Labels: size/L

#116 update to latest next.js version
  package-lock.json
  package.json
Labels: size/XS

#119 Only display the 'force verify' button to those with the 'verifier' role
  components/SubmitMatches/MatchForm/MatchForm.tsx
Labels: size/XS

#120 Develop
  app/actions.ts
  app/auth/route.ts
  app/submit/page.tsx
  components/SubmitMatches/MatchForm/MatchForm.tsx
  lib/types.ts
  middleware.ts
  package-lock.json
  package.json
  util/UserLoggedContext.tsx
Labels: size/L

#121 Staging
  app/actions.ts
  app/auth/route.ts
  app/submit/page.tsx
  components/SubmitMatches/MatchForm/MatchForm.tsx
  lib/types.ts
  middleware.ts
  package-lock.json
  package.json
  util/ErrorContext.tsx
  util/UserLoggedContext.tsx
Labels: size/L

#124 Leaderboard players links and Rank icons implementation
  components/Dashboard/UserMainCard/UserMainCard.module.css
  components/Dashboard/UserMainCard/UserMainCard.tsx
  components/Dashboard/UserRatingProgressBar/UserRatingProgressBar.module.css
  components/Dashboard/UserRatingProgressBar/UserRatingProgressBar.tsx
  components/Leaderboard/Leaderboard.module.css
  components/Leaderboard/Leaderboard.tsx
  public/icons/ranks/Bronze I.svg
  public/icons/ranks/Bronze II.svg
  public/icons/ranks/Bronze III.svg
  public/icons/ranks/Diamond I.svg
  public/icons/ranks/Diamond II.svg
  public/icons/ranks/Diamond III.svg
  public/icons/ranks/Elite Grandmaster.svg
  public/icons/ranks/Emerald I.svg
  public/icons/ranks/Emerald II.svg
  public/icons/ranks/Emerald III.svg
  public/icons/ranks/Gold I.svg
  public/icons/ranks/Gold II.svg
  public/icons/ranks/Gold III.svg
  public/icons/ranks/Grandmaster I.svg
  public/icons/ranks/Grandmaster II.svg
  public/icons/ranks/Grandmaster III.svg
  public/icons/ranks/Master I.svg
  public/icons/ranks/Master II.svg
  public/icons/ranks/Master III.svg
  public/icons/ranks/Platinum I.svg
  public/icons/ranks/Platinum II.svg
  public/icons/ranks/Platinum III.svg
  public/icons/ranks/Silver I.svg
  public/icons/ranks/Silver II.svg
  public/icons/ranks/Silver III.svg
Labels: size/L

#130 Fix id mapping in leaderboard
  components/Leaderboard/Leaderboard.tsx
Labels: size/XS

#131 Remove alt origin env var
  app/actions.ts
Labels: size/XS

#132 Develop
  app/actions.ts
  components/Dashboard/UserMainCard/UserMainCard.module.css
  components/Dashboard/UserMainCard/UserMainCard.tsx
  components/Dashboard/UserRatingProgressBar/UserRatingProgressBar.module.css
  components/Dashboard/UserRatingProgressBar/UserRatingProgressBar.tsx
  components/Leaderboard/Leaderboard.module.css
  components/Leaderboard/Leaderboard.tsx
  public/icons/ranks/Bronze I.svg
  public/icons/ranks/Bronze II.svg
  public/icons/ranks/Bronze III.svg
  public/icons/ranks/Diamond I.svg
  public/icons/ranks/Diamond II.svg
  public/icons/ranks/Diamond III.svg
  public/icons/ranks/Elite Grandmaster.svg
  public/icons/ranks/Emerald I.svg
  public/icons/ranks/Emerald II.svg
  public/icons/ranks/Emerald III.svg
  public/icons/ranks/Gold I.svg
  public/icons/ranks/Gold II.svg
  public/icons/ranks/Gold III.svg
  public/icons/ranks/Grandmaster I.svg
  public/icons/ranks/Grandmaster II.svg
  public/icons/ranks/Grandmaster III.svg
  public/icons/ranks/Master I.svg
  public/icons/ranks/Master II.svg
  public/icons/ranks/Master III.svg
  public/icons/ranks/Platinum I.svg
  public/icons/ranks/Platinum II.svg
  public/icons/ranks/Platinum III.svg
  public/icons/ranks/Silver I.svg
  public/icons/ranks/Silver II.svg
  public/icons/ranks/Silver III.svg
Labels: size/L

#133 Staging
  app/actions.ts
  components/Dashboard/UserMainCard/UserMainCard.module.css
  components/Dashboard/UserMainCard/UserMainCard.tsx
  components/Dashboard/UserRatingProgressBar/UserRatingProgressBar.module.css
  components/Dashboard/UserRatingProgressBar/UserRatingProgressBar.tsx
  components/Leaderboard/Leaderboard.module.css
  components/Leaderboard/Leaderboard.tsx
  public/icons/ranks/Bronze I.svg
  public/icons/ranks/Bronze II.svg
  public/icons/ranks/Bronze III.svg
  public/icons/ranks/Diamond I.svg
  public/icons/ranks/Diamond II.svg
  public/icons/ranks/Diamond III.svg
  public/icons/ranks/Elite Grandmaster.svg
  public/icons/ranks/Emerald I.svg
  public/icons/ranks/Emerald II.svg
  public/icons/ranks/Emerald III.svg
  public/icons/ranks/Gold I.svg
  public/icons/ranks/Gold II.svg
  public/icons/ranks/Gold III.svg
  public/icons/ranks/Grandmaster I.svg
  public/icons/ranks/Grandmaster II.svg
  public/icons/ranks/Grandmaster III.svg
  public/icons/ranks/Master I.svg
  public/icons/ranks/Master II.svg
  public/icons/ranks/Master III.svg
  public/icons/ranks/Platinum I.svg
  public/icons/ranks/Platinum II.svg
  public/icons/ranks/Platinum III.svg
  public/icons/ranks/Silver I.svg
  public/icons/ranks/Silver II.svg
  public/icons/ranks/Silver III.svg
Labels: size/L

#139 Tooltip for rank icons and new Elite Grandmaster icon
  components/Leaderboard/Leaderboard.tsx
  package-lock.json
  package.json
  public/icons/ranks/Elite Grandmaster-Old.svg
  public/icons/ranks/Elite Grandmaster.svg
Labels: size/M

#141 Modified expiration for refreshToken cookie
  app/actions.ts
  app/auth/route.ts
Labels: size/S

#142 Fix leaderboard tiers filter with new API changes
  app/actions.ts
  app/leaderboards/page.tsx
  components/Collapsible/FiltersCollapsible/FiltersCollapsible.tsx
  components/TierSelector/TierSelector.tsx
  lib/types.ts
Labels: size/L

#144 Refactor 'roles' to 'scopes'
  app/actions.ts
  app/submit/page.tsx
  components/SubmitMatches/MatchForm/MatchForm.tsx
  lib/types.ts
Labels: size/S
