Repository osu-tournament-rating/otr-web, pull requests merged in 2024-06, with the labels that each got.

#191 Change .env.example to new values
  .env.example
Labels: size/S

#192 Recent tournament performances
  app/dashboard/page.tsx
  app/users/[id]/page.tsx
  components/Charts/BarChart/BarChart.tsx
Labels: bug, type:feature, area:dashboard, size/M, area:profile

#188 New charts
  app/dashboard/page.tsx
  app/globals.css
  app/users/[id]/page.tsx
  components/Charts/AreaChart/AreaChart.tsx
  components/Charts/BarChart/BarChart.tsx
  components/Charts/DoughnutChart/DoughnutChart.module.css
  components/Charts/DoughnutChart/DoughnutChart.tsx
  components/Charts/InlineChart/InlineChart.module.css
  components/Charts/InlineChart/InlineChart.tsx
  components/Charts/MiddleBarChart/MiddleBarChart.module.css
  components/Charts/MiddleBarChart/MiddleBarChart.tsx
  components/Charts/PlayersBarChart/PlayersBarChart.tsx
  components/Charts/RadarChart/RadarChart.tsx
  components/Dashboard/FilterButtons/FilterButtons.tsx
  components/Dashboard/FilterChangeButton/FilterChangeButton.module.css
  components/Dashboard/GridCard/GridCard.module.css
  components/Dashboard/GridCard/GridCard.tsx
  components/Dashboard/Matches/UserTotalMatches/UserTotalMatches.module.css
  components/Dashboard/Matches/UserTotalMatches/UserTotalMatches.tsx
  components/Tooltip/Tooltip.tsx
  lib/chartjs-plugins/customChartBackground.ts
  lib/chartjs-plugins/customChartScaleXBackground.ts
  lib/chartjs-plugins/customChartScaleYBackground.ts
Labels: size/XXL

#197 License
  LICENSE.txt
Labels: size/XL
