Repository osu-tournament-rating/otr-web, pull requests merged in 2024-04, with the labels that each got.

#145 fix leaderboard params when changing page
  app/actions.ts
Labels: size/XS

#146 Dashboard error page
  app/dashboard/error.module.css
  app/dashboard/error.tsx
  app/dashboard/page.tsx
  components/NavBar/ModeSwitcher/ModeSwitcher.module.css
  public/images/error-background.svg
Labels: size/L

#151 Use new submission endpoint
  app/actions.ts
  components/ErrorToast/ErrorToast.module.css
  components/SubmitMatches/MatchForm/MatchForm.tsx
  lib/types.ts
  util/ErrorContext.tsx
Labels: area:tournaments, size/L

#152 Dark Mode Implementation
  app/dashboard/page.module.css
  app/globals.css
  app/layout.tsx
  app/page.module.css
  app/page.tsx
  components/Badges/Provisional/provisionalBadge.module.css
  components/Button/FilterChangeButton/FilterChangeButton.module.css
  components/Card/Card.module.css
  components/Charts/AreaChart/AreaChart.module.css
  components/Charts/AreaChart/AreaChart.tsx
  components/Charts/InlineChart/InlineChart.module.css
  components/Charts/RadarChart/RadarChart.tsx
  components/Collapsible/FiltersCollapsible/FiltersCollapsible.module.css
  components/Dashboard/FilterChangeButton/FilterChangeButton.module.css
  components/Dashboard/GridCard/GridCard.module.css
  components/Dashboard/Matches/UserTotalMatches/UserTotalMatches.module.css
  components/Dashboard/UserMainCard/UserMainCard.module.css
  components/Footer/Footer.module.css
  components/Form/Form.module.css
  components/Leaderboard/Leaderboard.module.css
  components/Leaderboard/Leaderboard.tsx
  components/Leaderboard/UserStats/UserStats.module.css
  components/NavBar/HamburgerMobile/HamburgerMobile.module.css
  components/NavBar/ModeSwitcher/ModeSwitcher.module.css
  components/NavBar/NavBar.module.css
  components/NavBar/NavBar.tsx
  components/NavBar/ThemeSwitcher/ThemeSwitcher.module.css
  components/NavBar/ThemeSwitcher/ThemeSwitcher.tsx
  components/Range/RangeSlider.module.css
  components/SubmitMatches/MatchForm/MatchForm.module.css
  package-lock.json
  package.json
  public/icons/sun.svg
  public/logos/full-logo-dark.svg
Labels: size/L, type:ui/ux

#153 Fix dark mode user profile and homepage logo
  app/page.module.css
  app/page.tsx
  app/users/[id]/page.module.css
  components/Homepage/Logo/Logo.module.css
  components/Homepage/Logo/Logo.tsx
  components/Profile/UserMainCard/UserMainCard.module.css
Labels: size/M

#155 Switch theme with keybind
  components/NavBar/ThemeSwitcher/ThemeSwitcher.tsx
  package-lock.json
  package.json
Labels: size/S

#156 Implementation of search bar
  app/actions.ts
  app/globals.css
  components/NavBar/NavBar.tsx
  components/NavBar/SearchButton/SearchButton.module.css
  components/NavBar/SearchButton/SearchButton.tsx
  components/SearchBar/SearchBar.module.css
  components/SearchBar/SearchBar.tsx
  package-lock.json
  package.json
  public/icons/search.svg
Labels: size/XL

#158 Develop
  app/actions.ts
  app/auth/route.ts
  app/dashboard/error.module.css
  app/dashboard/error.tsx
  app/dashboard/page.module.css
  app/dashboard/page.tsx
  app/globals.css
  app/layout.tsx
  app/leaderboards/page.tsx
  app/page.module.css
  app/page.tsx
  app/submit/page.tsx
  app/users/[id]/page.module.css
  components/Badges/Provisional/provisionalBadge.module.css
  components/Button/FilterChangeButton/FilterChangeButton.module.css
  components/Card/Card.module.css
  components/Charts/AreaChart/AreaChart.module.css
  components/Charts/AreaChart/AreaChart.tsx
  components/Charts/InlineChart/InlineChart.module.css
  components/Charts/RadarChart/RadarChart.tsx
  components/Collapsible/FiltersCollapsible/FiltersCollapsible.module.css
  components/Collapsible/FiltersCollapsible/FiltersCollapsible.tsx
  components/Dashboard/FilterChangeButton/FilterChangeButton.module.css
  components/Dashboard/GridCard/GridCard.module.css
  components/Dashboard/Matches/UserTotalMatches/UserTotalMatches.module.css
  components/Dashboard/UserMainCard/UserMainCard.module.css
  components/ErrorToast/ErrorToast.module.css
  components/Footer/Footer.module.css
  components/Form/Form.module.css
  components/Homepage/Logo/Logo.module.css
  components/Homepage/Logo/Logo.tsx
  components/Leaderboard/Leaderboard.module.css
  components/Leaderboard/Leaderboard.tsx
  components/Leaderboard/UserStats/UserStats.module.css
  components/NavBar/HamburgerMobile/HamburgerMobile.module.css
  components/NavBar/ModeSwitcher/ModeSwitcher.module.css
  components/NavBar/NavBar.module.css
  components/NavBar/NavBar.tsx
  components/NavBar/SearchButton/SearchButton.module.css
  components/NavBar/SearchButton/SearchButton.tsx
  components/NavBar/ThemeSwitcher/ThemeSwitcher.module.css
  components/NavBar/ThemeSwitcher/ThemeSwitcher.tsx
  components/Profile/UserMainCard/UserMainCard.module.css
  components/Profile/UserMainCard/UserMainCard.tsx
  components/Range/RangeSlider.module.css
  components/SearchBar/SearchBar.module.css
  components/SearchBar/SearchBar.tsx
  components/SubmitMatches/MatchForm/MatchForm.module.css
  components/SubmitMatches/MatchForm/MatchForm.tsx
  components/TierSelector/TierSelector.tsx
  lib/types.ts
  package-lock.json
  package.json
  public/icons/ranks/Elite Grandmaster-Old.svg
  public/icons/ranks/Elite Grandmaster.svg
  public/icons/search.svg
  public/icons/sun.svg
  public/images/error-background.svg
  public/logos/full-logo-dark.svg
  util/ErrorContext.tsx
Labels: size/XXL

#159 Staging
  app/actions.ts
  app/auth/route.ts
  app/dashboard/error.module.css
  app/dashboard/error.tsx
  app/dashboard/page.module.css
  app/dashboard/page.tsx
  app/globals.css
  app/layout.tsx
  app/leaderboards/page.tsx
  app/page.module.css
  app/page.tsx
  app/submit/page.tsx
  app/users/[id]/page.module.css
  components/Badges/Provisional/provisionalBadge.module.css
  components/Button/FilterChangeButton/FilterChangeButton.module.css
  components/Card/Card.module.css
  components/Charts/AreaChart/AreaChart.module.css
  components/Charts/AreaChart/AreaChart.tsx
  components/Charts/InlineChart/InlineChart.module.css
  components/Charts/RadarChart/RadarChart.tsx
  components/Collapsible/FiltersCollapsible/FiltersCollapsible.module.css
  components/Collapsible/FiltersCollapsible/FiltersCollapsible.tsx
  components/Dashboard/FilterChangeButton/FilterChangeButton.module.css
  components/Dashboard/GridCard/GridCard.module.css
  components/Dashboard/Matches/UserTotalMatches/UserTotalMatches.module.css
  components/Dashboard/UserMainCard/UserMainCard.module.css
  components/ErrorToast/ErrorToast.module.css
  components/Footer/Footer.module.css
  components/Form/Form.module.css
  components/Homepage/Logo/Logo.module.css
  components/Homepage/Logo/Logo.tsx
  components/Leaderboard/Leaderboard.module.css
  components/Leaderboard/Leaderboard.tsx
  components/Leaderboard/UserStats/UserStats.module.css
  components/NavBar/HamburgerMobile/HamburgerMobile.module.css
  components/NavBar/ModeSwitcher/ModeSwitcher.module.css
  components/NavBar/NavBar.module.css
  components/NavBar/NavBar.tsx
  components/NavBar/SearchButton/SearchButton.module.css
  components/NavBar/SearchButton/SearchButton.tsx
  components/NavBar/ThemeSwitcher/ThemeSwitcher.module.css
  components/NavBar/ThemeSwitcher/ThemeSwitcher.tsx
  components/Profile/UserMainCard/UserMainCard.module.css
  components/Profile/UserMainCard/UserMainCard.tsx
  components/Range/RangeSlider.module.css
  components/SearchBar/SearchBar.module.css
  components/SearchBar/SearchBar.tsx
  components/SubmitMatches/MatchForm/MatchForm.module.css
  components/SubmitMatches/MatchForm/MatchForm.tsx
  components/TierSelector/TierSelector.tsx
  lib/types.ts
  package-lock.json
  package.json
  public/icons/ranks/Elite Grandmaster-Old.svg
  public/icons/ranks/Elite Grandmaster.svg
  public/icons/search.svg
  public/icons/sun.svg
  public/images/error-background.svg
  public/logos/full-logo-dark.svg
  util/ErrorContext.tsx
Labels: size/XXL

#162 Fix rename generalStats to baseStats
  app/dashboard/page.tsx
  app/users/[id]/page.tsx
  components/Profile/UserMainCard/UserMainCard.tsx
Labels: size/M

#161 Fixes to searchbar
  app/actions.ts
  components/SearchBar/SearchBar.tsx
Labels: size/S

#163 Leaderboard reflects selected gamemode
  app/actions.ts
Labels: size/XS

#164 User keys rename
  app/actions.ts
Labels: size/S

#165 Develop
  app/actions.ts
  components/SearchBar/SearchBar.tsx
Labels: size/M

#168 Staging
  app/dashboard/page.tsx
  app/users/[id]/page.tsx
  components/Profile/UserMainCard/UserMainCard.tsx
Labels: size/M

#167 Staging
  app/actions.ts
  components/SearchBar/SearchBar.tsx
Labels: size/M

#171 First fixes to charts
  components/Charts/AreaChart/AreaChart.module.css
  components/Charts/BarChart/BarChart.module.css
  components/Charts/DoughnutChart/DoughnutChart.module.css
  components/Charts/PlayersBarChart/PlayersBarChart.module.css
  components/Charts/PlayersBarChart/PlayersBarChart.tsx
  components/Charts/RadarChart/RadarChart.module.css
  components/Dashboard/GridCard/GridCard.module.css
  components/Dashboard/GridCard/GridCard.tsx
Labels: size/M
