Repository osu-tournament-rating/otr-web, pull requests merged in 2024-12, with the labels that each got.

#233 Various improvements & bug fixes
  app/actions.ts
  components/Leaderboard/Leaderboard.tsx
  components/Tournaments/InfoContainer/InfoContainer.tsx
  components/Tournaments/MainExpandableRow/MainExpandableRow.tsx
Labels: bug, size/M

#232 fix form resetting on successful submission
  app/actions/tournaments.ts
  components/Tournaments/Submission/SubmissionForm/SubmissionForm.tsx
Labels: size/S

#237 hotfix match id parsing
  app/actions/tournaments.ts
Labels: bug, area:tournaments, size/XS

#235 Introduce partial typing for player statistics fetching
  app/actions.ts
  app/actions/players.ts
  app/players/[id]/page.tsx
  components/Charts/AreaChart/AreaChart.tsx
Labels: area:dashboard, area:stats, size/L, type:code-quality, area:profile
