Repository osu-tournament-rating/otr-web, pull requests merged in 2024-08, with the labels that each got.

#200 Navbar Tooltip
  .prettierrc
  app/globals.css
  components/NavBar/NavBar.module.css
  components/NavBar/NavBar.tsx
  components/NavBar/ThemeSwitcher/ThemeSwitcher.tsx
  components/NavBar/Tooltip/Tooltip.module.css
  components/NavBar/Tooltip/Tooltip.tsx
  components/NavBar/UserLogged/UserLogged.tsx
  package-lock.json
  package.json
Labels: size/L

#203 Submission form split mania to 4k and 7k
  components/SubmitMatches/MatchForm/MatchForm.tsx
  lib/types.ts
Labels: size/S

#213 Changing Team Size to Format
  app/actions.ts
  components/NavBar/Routes/Routes.tsx
  components/SubmitMatches/MatchForm/MatchForm.tsx
  lib/types.ts
Labels: size/M

#215 Searchbar teamSize rename to lobbySize
  components/SearchBar/SearchBar.tsx
Labels: size/XS

#216 Reword mode to ruleset
  app/actions.ts
  components/SubmitMatches/MatchForm/MatchForm.tsx
Labels: size/XS

#217 New SVGs rules
  app/globals.css
  app/not-found.tsx
  app/page.tsx
  app/players/[id]/not-found.tsx
  components/Dashboard/NoDataContainer/NoDataContainer.module.css
  components/Dashboard/NoDataContainer/NoDataContainer.tsx
  components/Dashboard/UserMainCard/UserMainCard.module.css
  components/Dashboard/UserMainCard/UserMainCard.tsx
  components/Homepage/Logo/Logo.tsx
  components/NavBar/ModeSwitcher/ModeSwitcher.tsx
  components/NavBar/NavBar.module.css
  components/NavBar/NavBar.tsx
  components/NavBar/SearchButton/SearchButton.module.css
  components/NavBar/SearchButton/SearchButton.tsx
  components/NavBar/ThemeSwitcher/ThemeSwitcher.module.css
  components/NavBar/ThemeSwitcher/ThemeSwitcher.tsx
  components/SearchBar/SearchBar.module.css
  components/SearchBar/SearchBar.tsx
  next.config.js
  package-lock.json
  package.json
  svgr.d.ts
  tsconfig.json
Labels: size/L

#218 Sign out function
  app/actions.ts
  components/NavBar/NavBar.module.css
  components/NavBar/Tooltip/Tooltip.module.css
  components/NavBar/UserLogged/UserLogged.tsx
Labels: size/M
