Repository osu-tournament-rating/otr-web, pull requests merged in 2024-02, with the labels that each got.

#96 Hide donate button for unauthorized users
  components/Footer/Footer.tsx
  components/NavBar/NavBar.tsx
  components/NavBar/Routes/Routes.tsx
Labels: size/S

#98 User friendly error visualization
  README.md
  app/actions.ts
  app/globals.css
  app/layout.tsx
  app/unauthorized/page.tsx
  components/ErrorToast/ErrorToast.module.css
  components/ErrorToast/ErrorToast.tsx
  components/LayoutProvider/LayoutProvider.tsx
  components/NavBar/NavBar.tsx
  components/NavBar/Routes/Routes.tsx
  util/ErrorContext.tsx
  util/hooks.ts
Labels: size/L

#99 Dashboard and User pages update following api changes
  app/actions.ts
  app/dashboard/page.module.css
  app/dashboard/page.tsx
  app/users/[id]/page.module.css
  app/users/[id]/page.tsx
  components/Charts/AreaChart/AreaChart.tsx
  util/ErrorContext.tsx
Labels: size/L

#100 Error toast fix to empty text
  util/ErrorContext.tsx
Labels: size/XS

#105 Added current day in rating graph
  components/Charts/AreaChart/AreaChart.module.css
  components/Charts/AreaChart/AreaChart.tsx
  package-lock.json
  package.json
Labels: size/M

#106 Merge develop: breaking changes from last week
  README.md
  app/actions.ts
  app/dashboard/page.module.css
  app/dashboard/page.tsx
  app/globals.css
  app/layout.tsx
  app/unauthorized/page.tsx
  app/users/[id]/page.module.css
  app/users/[id]/page.tsx
  components/Charts/AreaChart/AreaChart.module.css
  components/Charts/AreaChart/AreaChart.tsx
  components/ErrorToast/ErrorToast.module.css
  components/ErrorToast/ErrorToast.tsx
  components/Footer/Footer.tsx
  components/LayoutProvider/LayoutProvider.tsx
  components/NavBar/NavBar.tsx
  package-lock.json
  package.json
  util/ErrorContext.tsx
  util/hooks.ts
Labels: size/L

#107 Staging
  README.md
  app/actions.ts
  app/dashboard/page.module.css
  app/dashboard/page.tsx
  app/globals.css
  app/layout.tsx
  app/unauthorized/page.tsx
  app/users/[id]/page.module.css
  app/users/[id]/page.tsx
  components/Charts/AreaChart/AreaChart.module.css
  components/Charts/AreaChart/AreaChart.tsx
  components/ErrorToast/ErrorToast.module.css
  components/ErrorToast/ErrorToast.tsx
  components/Footer/Footer.tsx
  components/LayoutProvider/LayoutProvider.tsx
  components/NavBar/NavBar.tsx
  package-lock.json
  package.json
  util/ErrorContext.tsx
  util/hooks.ts
Labels: size/L
