Repository osu-tournament-rating/otr-web, pull requests merged in 2025-06, with the labels that each got.

#382 Fix missing leaderboard tooltips
  app/layout.tsx
  app/leaderboard/columns.tsx
  app/leaderboard/data-table.tsx
  components/dates/FormattedDate.tsx
  components/icons/TierIcon.tsx
  components/shared/DeleteButton.tsx
  components/simple-tooltip.tsx
  components/tournaments/AcceptPreVerificationStatusesButton.tsx
  components/tournaments/DeleteTournamentBeatmapsButton.tsx
  components/tournaments/ResetAutomatedChecksButton.tsx
  components/tournaments/list/TournamentListFilter.tsx
  components/ui/table.tsx
  components/ui/tooltip.tsx
Labels: bug, size/L

#383 Remove unused imports
  components/dates/FormattedDate.tsx
  components/shared/DeleteButton.tsx
  components/tournaments/AcceptPreVerificationStatusesButton.tsx
  components/tournaments/DeleteTournamentBeatmapsButton.tsx
  components/tournaments/ResetAutomatedChecksButton.tsx
  components/tournaments/list/TournamentListFilter.tsx
Labels: size/XS

#384 Add basic CI build check
  .github/workflows/ci.yml
  components/dates/FormattedDate.tsx
  components/simple-tooltip.tsx
  components/tournaments/DeleteTournamentBeatmapsButton.tsx
  components/tournaments/ResetAutomatedChecksButton.tsx
  lib/actions/matches.ts
Labels: size/L

#385 Fix crash on no scores, touch up borders on game card
  components/games/GameCard.tsx
Labels: bug, size/M

#386 Use country flag in more places
  app/leaderboard/columns.tsx
  components/games/ScoreCard.tsx
  components/player/PlayerCard.tsx
  components/player/PlayerRatingStatsCard.tsx
  components/player/PlayerTierProgress.tsx
  components/profile/ProfileCard.tsx
  components/shared/CountryFlag.tsx
  components/shared/StatCard.tsx
Labels: bug, size/L

#387 New mania icons
  public/icons/rulesets/legacy_mania4k.svg
  public/icons/rulesets/legacy_mania7k.svg
  public/icons/rulesets/mania4k.svg
  public/icons/rulesets/mania7k.svg
Labels: size/S

#388 Fix player chart display on mobile
  app/players/[id]/page.tsx
  components/icons/TierIcon.tsx
  components/player/PlayerModCountChart.tsx
  components/player/PlayerModStatsChart.tsx
  lib/utils/tierData.ts
Labels: size/M

#389 Navigate to ruleset-specific player page on click from leaderboard
  app/leaderboard/columns.tsx
Labels: bug, size/XS

#390 Fix ruleset navigation from leaderboards page, mobile UI improvements
  app/layout.tsx
  app/leaderboard/page.tsx
  app/matches/[id]/page.tsx
  app/players/[id]/page.tsx
  app/tournaments/[id]/page.tsx
  app/tournaments/page.tsx
  app/tournaments/submit/page.tsx
  components/games/ScoreCard.tsx
  components/player/PlayerModCountChart.tsx
  components/player/PlayerModStatsChart.tsx
  components/tournaments/TournamentSubmissionForm.tsx
  components/tournaments/list/TournamentList.tsx
  components/tournaments/list/TournamentListFilter.tsx
  public/icons/mods/ModHT.svg
  public/icons/mods/ModMR.svg
  public/icons/mods/ModRX.svg
  public/icons/mods/ModSO.svg
Labels: bug, size/L

#393 Fix crash when player has no rating history
  app/players/[id]/page.tsx
  components/player/PlayerRatingChart.tsx
  components/player/PlayerRatingChartSummaryStats.tsx
  components/player/PlayerRatingChartView.tsx
Labels: bug, size/S

#397 Font hotfix
  app/globals.css
  app/layout.tsx
Labels: bug, size/S

#399 Remove whitelist restrictions
  .env.example
  app/leaderboard/columns.tsx
  app/page.tsx
  app/tournaments/[id]/columns.tsx
  app/tournaments/[id]/page.tsx
  app/unauthorized/page.tsx
  components/games/BeatmapBackground.tsx
  components/games/GameCardHeader.tsx
  components/header/Header.tsx
  components/matches/MatchCard.tsx
  components/player/PlayerModCountChart.tsx
  components/player/PlayerRatingChartTooltip.tsx
  components/player/PlayerRatingChartView.tsx
  components/profile/ProfileCard.tsx
  components/search/SearchDialog.tsx
  components/tournaments/TournamentBeatmapsView.tsx
  components/tournaments/TournamentPlayerStatsDashboard.tsx
  components/tournaments/TournamentTopPerformers.tsx
  components/tournaments/list/TournamentList.tsx
  lib/utils/tierData.ts
  middleware.ts
  public/images/beatmap-background-narrow.png
Labels: bug, size/L

#405 A few more fixes
  components/admin-notes/AdminNoteView.tsx
  components/player/PlayerRatingChartView.tsx
Labels: bug, size/S

#406 Fix percentile bug
  components/player/PlayerRatingStatsCard.tsx
Labels: bug, size/XS

#408 Fix match search result items
  components/search/MatchSearchResult.tsx
Labels: size/S

#424 Fix bug where external link issue would reproduce when `IS_RESTRICTED_ENVIRONMENT=true`
  middleware.ts
Labels: bug, size/XS

#425 Fix bug where users could see admin note entry box
  components/admin-notes/AdminNoteView.tsx
Labels: bug, size/M

#426 Use date-based versioning for production deployments
  .github/workflows/deploy-trigger.yml
  .github/workflows/deploy.yml
Labels: size/S

#437 Decode URI parameters when looking up players
  app/players/[id]/page.tsx
Labels: bug, size/S

#431 Rewrite formatted timestamp component
  components/dates/FormattedDate.tsx
Labels: size/S

#445 fix chart heights on stats page
  components/stats/TournamentVerificationChart.tsx
  components/stats/TournamentsByRulesetChart.tsx
  lib/utils/chart.ts
Labels: size/XS

#446 Fix comma bug display when beatmaps have multiple diff owners
  .gitignore
  components/games/GameCardHeader.tsx
Labels: bug, size/XS

#449 Update to API client v1.1.0 and handle DTO changes
  app/matches/[id]/page.tsx
  app/tournaments/[id]/page.tsx
  components/games/MergeGameButton.tsx
  components/matches/MatchAdminView.tsx
  components/matches/MergeMatchButton.tsx
  lib/actions/games.ts
  lib/actions/matches.ts
  lib/actions/tournaments.ts
  lib/utils/form.ts
  package-lock.json
  package.json
Labels: size/L

#435 Readd country flag & Add country rank
  app/leaderboard/columns.tsx
  components/shared/CountryFlag.tsx
Labels: size/S

#453 Add country filtering for leaderboard
  app/leaderboard/columns.tsx
  components/leaderboard/CountryFilter.tsx
  components/leaderboard/LeaderboardFilter.tsx
  components/select/multiple-select.tsx
  lib/schema.ts
  lib/utils/leaderboard.ts
  package-lock.json
  package.json
Labels: size/L

#451 Add filtering tools
  .prettierrc
  app/globals.css
  app/leaderboard/columns.tsx
  app/tools/filter-reports/page.tsx
  app/tools/filter/page.tsx
  components/buttons/RulesetSelector.tsx
  components/filtering/BetaWarningBanner.tsx
  components/filtering/FailureReasonsBadges.tsx
  components/filtering/FilterComplianceNotice.tsx
  components/filtering/FilterReportView.tsx
  components/filtering/FilteringForm.tsx
  components/filtering/FilteringResultsTable.tsx
  components/filtering/PlayerCell.tsx
  components/filtering/StatusIcon.tsx
  components/filtering/tableHelpers.tsx
  components/header/Header.tsx
  components/leaderboard/LeaderboardFilter.tsx
  components/ui/alert.tsx
  lib/actions/auth.ts
  lib/actions/filtering.ts
  lib/api/server.ts
  lib/enums.ts
  lib/utils/csv.ts
  lib/utils/date.ts
  lib/utils/error.ts
  package-lock.json
  package.json
Labels: size/XXL
