Repository osu-tournament-rating/otr-web, pull requests merged in 2025-02, with the labels that each got.

#253 tournament admin view with minimal functionality
  app/actions/tournaments.ts
  app/tournaments/[id]/page.tsx
  components/Tournaments/AdminView/TournamentAdminView.tsx
  components/Tournaments/PageContent/TournamentPageContent.module.css
  components/Tournaments/PageContent/TournamentPageHeader.tsx
  components/Tournaments/TournamentPageContent/TournamentPageHeader.tsx
  lib/api.ts
Labels: size/L

#255 Implement functionality for the tournaments search bar
  components/Context/TournamentListFilterContext.tsx
  components/Tournaments/TournamentList/Filter/TournamentListFilter.tsx
  components/Tournaments/TournamentList/Filter/TournamentListFilterCollapsible.tsx
  components/Tournaments/TournamentList/TournamentList.tsx
  lib/dates.ts
  lib/enums.ts
  lib/schemas.ts
  public/icons/ctb.svg
  public/icons/mania.svg
  public/icons/osu.svg
  public/icons/rulesets/all.svg
  public/icons/rulesets/catch.svg
  public/icons/rulesets/mania.svg
  public/icons/rulesets/mania4k.svg
  public/icons/rulesets/mania7k.svg
  public/icons/rulesets/osu.svg
  public/icons/rulesets/taiko.svg
  public/icons/taiko.svg
Labels: size/L

#257 Sonner toasts, admin panel visual feedback, game verification preview
  app/actions/common.ts
  app/actions/tournaments.ts
  app/layout.tsx
  components/ErrorToast/ErrorToast.module.css
  components/ErrorToast/ErrorToast.tsx
  components/Matches/List/MatchesListItem.tsx
  components/Toast/Toast.module.css
  components/Toast/Toast.tsx
  components/Toasts/ConfiguredToaster.tsx
  components/Tournaments/AdminView/TournamentAdminView.tsx
  components/Tournaments/Submission/SubmissionForm/SubmissionForm.tsx
  components/Tournaments/TournamentList/Filter/TournamentListFilter.tsx
  components/Tournaments/TournamentList/TournamentList.module.css
  lib/api.ts
  lib/dates.ts
  lib/enums.ts
  lib/schemas.ts
  lib/types.ts
  package-lock.json
  package.json
  util/ErrorContext.tsx
  util/hooks.ts
Labels: size/XL

#259 New design for the match page
  app/globals.css
  components/Enums/ModsDisplay/ModsDisplay.tsx
  components/Games/InfoContainer/GameInfoContainer.tsx
  components/Games/List/GamesList.tsx
  components/Games/List/ListItem/GamesListItem.module.css
  components/Games/List/ListItem/GamesListItem.tsx
  components/Games/List/ListItem/GamesListItemFooter.tsx
  components/Games/List/ListItem/GamesListItemHeader.tsx
  components/Matches/List/MatchesListItem.tsx
  components/Scores/GameScore.module.css
  components/Scores/GameScore.tsx
  components/Tournaments/VerificationStatusCircle/VerificationStatusCircle.module.css
  components/Tournaments/VerificationStatusCircle/VerificationStatusCircle.tsx
  next.config.ts
  package-lock.json
  package.json
  public/icons/mods/ModDT.svg
  public/icons/mods/ModEZ.svg
  public/icons/mods/ModFL.svg
  public/icons/mods/ModFL2.svg
  public/icons/mods/ModFM.svg
  public/icons/mods/ModHD.svg
  public/icons/mods/ModHR.svg
  public/icons/mods/ModNF.svg
  public/icons/mods/ModNM.svg
Labels: size/XXL

#261 Use api client for search
  app/actions.ts
  app/actions/search.ts
  components/SearchBar/SearchBar.tsx
Labels: bug, area:search, size/L
