Repository osu-tournament-rating/otr-web, pull requests merged in 2025-05, with the labels that each got.

#311 Design cleanup
  app/globals.css
  app/matches/[id]/page.tsx
  app/page.tsx
  app/tournaments/page.tsx
  app/tournaments/submit/page.tsx
  components/badges/VerificationBadge.tsx
  components/header/Header.tsx
  components/home/FeatureCard.tsx
  components/home/LinkCard.tsx
  components/rating/RatingLadder.tsx
  components/rating/TierCard.tsx
  components/tournaments/TournamentSubmissionForm.tsx
  components/tournaments/list/TournamentListFilter.tsx
  components/ui/button.tsx
  components/ui/toggle-group.tsx
Labels: size/L

#314 Merge new color scheme into player page branch
  app/globals.css
  app/matches/[id]/page.tsx
  app/page.tsx
  app/tournaments/page.tsx
  app/tournaments/submit/page.tsx
  components/badges/VerificationBadge.tsx
  components/home/FeatureCard.tsx
  components/home/LinkCard.tsx
  components/rating/RatingLadder.tsx
  components/rating/TierCard.tsx
  components/search/PlayerSearchResult.tsx
  components/tournaments/TournamentSubmissionForm.tsx
  components/tournaments/list/TournamentListFilter.tsx
  components/ui/button.tsx
  components/ui/toggle-group.tsx
  package-lock.json
Labels: size/L

#315 fix linting errors
  app/layout.tsx
  components/dates/FormattedDate.tsx
Labels: size/XS

#318 Use server actions, fix doc links
  app/tournaments/submit/page.tsx
  components/tournaments/list/TournamentList.tsx
  lib/actions/search.ts
  lib/hooks/useSearch.ts
Labels: bug, size/M

#320 Fix ruleset filter, head to head display crash
  app/leaderboard/page.tsx
  components/games/GameCard.tsx
Labels: size/S

#323 Fix env casing
  .github/CODEOWNERS
  .github/workflows/deploy-trigger.yml
  .github/workflows/deploy.yml
Labels: size/XS

#335 Finalize player page design
  app/globals.css
  components/buttons/RulesetSelector.tsx
  components/player/PlayerCard.tsx
  components/player/PlayerRatingChart.tsx
  components/player/StatCard.tsx
  components/rating/TRText.tsx
  components/ui/tabs.tsx
  lib/utils.ts
  lib/utils/mods.ts
Labels: size/L

#338 Player page spacing and metadata fixes
  app/players/[id]/page.tsx
  components/buttons/RulesetSelector.tsx
  components/icons/RulesetIcon.tsx
  components/player/PlayerModCountChart.tsx
  components/player/PlayerRatingChartSummaryStats.tsx
  components/profile/ProfileCard.tsx
  components/search/MatchSearchResult.tsx
  components/search/PlayerSearchResult.tsx
  components/search/SearchDialog.tsx
  components/search/SearchResults.tsx
  components/search/TournamentSearchResult.tsx
  lib/actions/players.ts
  package-lock.json
  package.json
Labels: bug, size/L, type:ui/ux

#340 Cleanup color usage
  app/globals.css
  components/admin-notes/AdminNoteView.tsx
  components/games/GameCardHeader.tsx
  components/matches/MatchCard.tsx
  components/player/PlayerRatingChartSummaryStats.tsx
  components/player/PlayerRatingChartTable.tsx
  components/player/PlayerRatingChartTooltip.tsx
Labels: size/M

#342 Comment unused imports (temporarily)
  app/tournaments/[id]/page.tsx
Labels: size/XS

#343 Fix stale state after entity edits
  app/tournaments/[id]/page.tsx
  components/admin-notes/AdminNoteListItem.tsx
  components/admin-notes/AdminNoteView.tsx
  components/games/GameAdminView.tsx
  components/matches/MatchAdminView.tsx
  components/scores/ScoreAdminView.tsx
  components/tournaments/TournamentAdminView.tsx
  components/ui/button.tsx
Labels: bug

#357 Remove hover effect of score card team color for non-admin users
  components/games/ScoreCard.tsx
  components/games/ScoreTeamColorBar.tsx
Labels: size/M

#373 Beatmap tab fixes, tournament external link
  app/tournaments/[id]/page.tsx
  components/tournaments/TournamentBeatmapsView.tsx
Labels: size/M

#374 Update tournament beatmaps table
  app/tournaments/[id]/page.tsx
  components/icons/SingleModIcon.tsx
  components/tournaments/TournamentBeatmapsView.tsx
  lib/utils/mods.ts
Labels: size/XL

#375 Fix freeze on tournament page ruleset select
  components/tournaments/list/TournamentListFilter.tsx
  package-lock.json
  package.json
Labels: size/L
