Repository osu-tournament-rating/otr-web, pull requests merged in 2025-04, with the labels that each got.

#281 Improve nav UI
  components/header/Header.tsx
Labels: size/S

#286 Mobile leaderboard improvements
  .gitignore
  app/leaderboard/columns.tsx
  app/leaderboard/data-table.tsx
  app/leaderboard/page.tsx
Labels: size/M

#277 Functional search implementation
  app/globals.css
  components/search/MatchSearchResult.tsx
  components/search/PlayerSearchResult.tsx
  components/search/SearchDialog.tsx
  components/search/SearchResults.tsx
  components/search/TournamentSearchResult.tsx
  lib/hooks/useSearch.ts
  lib/utils/search.tsx
  next.config.ts
  package-lock.json
  package.json
Labels: size/L

#288 Home page
  app/globals.css
  app/page.tsx
  components/footer/Footer.tsx
  components/home/FeatureCard.tsx
  components/home/LinkCard.tsx
  components/icons/TierIcon.tsx
  components/rating/RatingLadder.tsx
  components/rating/TierCard.tsx
  components/search/PlayerSearchResult.tsx
  components/search/TournamentSearchResult.tsx
  lib/tierData.ts
  package-lock.json
Labels: size/XL

#289 Submission page with color fixes and mobile navbar improvements
  app/matches/[id]/page.tsx
  app/tournaments/submit/page.tsx
  app/unauthorized/page.tsx
  components/badges/WarningFlagsBadge.tsx
  components/header/Header.tsx
  components/header/MobileNavTrigger.tsx
  components/profile/ProfileCard.tsx
  components/search/SearchDialog.tsx
  components/select/RulesetSelectContent.tsx
  components/select/multiple-select.tsx
  components/tournaments/TournamentSubmissionForm.tsx
  components/ui/LabelWithTooltip.tsx
  components/ui/checkbox.tsx
  lib/actions/tournaments.ts
  lib/api.ts
  lib/schema.ts
  package-lock.json
  package.json
Labels: size/XXL

#291 Unify and update deployment workflows
  .github/workflows/deploy.yml
  .github/workflows/prod-deploy.yml
  .github/workflows/staging-deploy.yml
  Dockerfile
Labels: size/L

#290 Add donation links to navbar and footer
  components/buttons/SupportButton.tsx
  components/footer/Footer.tsx
  components/header/Header.tsx
Labels: size/M

#284 Score editing, full admin note support, various UI fixes and improvements
  app/globals.css
  app/layout.tsx
  app/leaderboard/columns.tsx
  app/matches/[id]/page.tsx
  app/page.tsx
  components/admin-notes/AdminNoteCard.tsx
  components/admin-notes/AdminNoteForm.tsx
  components/admin-notes/AdminNoteList.tsx
  components/admin-notes/AdminNoteListItem.tsx
  components/admin-notes/AdminNoteView.tsx
  components/badges/VerificationBadge.tsx
  components/footer/Footer.tsx
  components/games/GameAdminView.tsx
  components/games/GameCard.tsx
  components/games/GameCardHeader.tsx
  components/games/ScoreCard.tsx
  components/icons/ModIconset.tsx
  components/matches/MatchAdminView.tsx
  components/matches/MatchCard.tsx
  components/scores/ScoreAdminView.tsx
  components/search/SearchDialog.tsx
  components/tournaments/TournamentAdminView.tsx
  components/tournaments/TournamentCard.tsx
  components/ui/alert-dialog.tsx
  components/ui/button.tsx
  lib/actions/admin-notes.ts
  lib/actions/scores.ts
  lib/api.ts
  lib/enums.ts
  lib/schema.ts
  lib/utils/toasts.ts
  package-lock.json
  package.json
Labels: size/XXL

#292 Tournaments page
  app/globals.css
  app/tournaments/page.tsx
  components/header/Header.tsx
  components/search/SearchDialog.tsx
  components/tournaments/TournamentAdminView.tsx
  components/tournaments/list/TournamentList.tsx
  components/tournaments/list/TournamentListFilter.tsx
  components/ui/selection-group.tsx
  components/ui/skeleton.tsx
  lib/actions/tournaments.ts
  lib/hooks/useSearch.ts
  lib/schema.ts
  lib/types.ts
  lib/utils/number.ts
  next.config.ts
  package-lock.json
  package.json
Labels: size/XL

#294 Lint format
  app/leaderboard/columns.tsx
  app/leaderboard/data-table.tsx
  components/badges/WarningFlagsBadge.tsx
  components/client-only.tsx
  components/home/FeatureCard.tsx
  components/leaderboard/LeaderboardFilter.tsx
  components/matches/MatchAdminView.tsx
  components/rating/RatingLadder.tsx
  components/rating/TierCard.tsx
  components/select/multiple-select.tsx
  components/tournaments/TournamentSubmissionForm.tsx
  components/ui/LabelWithTooltip.tsx
  components/ui/alert-dialog.tsx
  components/ui/avatar.tsx
  components/ui/checkbox.tsx
  components/ui/collapsible.tsx
  components/ui/dialog.tsx
  components/ui/dropdown-menu.tsx
  components/ui/navigation-menu.tsx
  components/ui/popover.tsx
  components/ui/select.tsx
  components/ui/sheet.tsx
  components/ui/tooltip.tsx
  lib/schema.ts
  lib/tierData.ts
Labels: size/L

#296 Deploy matrix fix
  .github/workflows/deploy.yml
Labels: size/S

#297 Deployment trigger calls reusable workflow
  .github/workflows/deploy-trigger.yml
  .github/workflows/deploy.yml
Labels: size/M

#298 split deploy trigger into two jobs
  .github/workflows/deploy-trigger.yml
Labels: size/S

#299 Add missing environment configuration
  .github/workflows/deploy-trigger.yml
  .github/workflows/deploy.yml
Labels: size/S

#301 Inherit secrets
  .github/workflows/deploy-trigger.yml
  .github/workflows/deploy.yml
Labels: size/XS

#309 Fix Dockerfile, build issues, update to latest otr-api client package
  .github/CODEOWNERS
  Dockerfile
  app/leaderboard/columns.tsx
  auth.ts
  next.config.ts
  package-lock.json
  package.json
Labels: size/L

#310 Package fix part 2
  package-lock.json
  package.json
Labels: size/XS
