Repository osu-tournament-rating/otr-web, pull requests merged in 2025-09, with the labels that each got.

#493 Update readme, remove overrides, pnpm lock
  README.md
  package-lock.json
  package.json
  pnpm-lock.yaml
Labels: size/XS

#502 remove unnecessary log statement
  components/buttons/RulesetSelector.tsx
Labels: size/XS

#507 Hard code red team left, blue team right (and no team underneath)
  components/games/GameCard.tsx
Labels: size/M

#508 Reset "Reject this tournament on submission" checkbox on submission
  components/tournaments/TournamentSubmissionForm.tsx
Labels: size/XS

#506 Display hit judgments based on ruleset
  components/games/ScoreCard.tsx
Labels: size/M

#526 Add procedure logging and audit functionality
  .env.example
  apps/web/app/server/oRPC/procedures/base.ts
  apps/web/app/server/oRPC/procedures/games/adminProcedures.ts
  apps/web/app/server/oRPC/procedures/matches/adminProcedures.ts
  apps/web/app/server/oRPC/procedures/scores/adminProcedures.ts
  apps/web/app/server/oRPC/procedures/tournaments/__tests__/tournamentRefetchMatchDataProcedure.test.ts
  apps/web/app/server/oRPC/procedures/tournaments/__tests__/tournamentSubmissionProcedure.test.ts
  apps/web/app/server/oRPC/procedures/tournaments/adminProcedures.ts
  apps/web/app/server/oRPC/procedures/tournaments/tournamentSubmissionProcedure.ts
  apps/web/drizzle/0003_audit_triggers.sql
  apps/web/drizzle/meta/_journal.json
  apps/web/lib/auth/auth.ts
  apps/web/package-lock.json
  bun.lock
  package.json
  packages/otr-core/src/db/audit.ts
  packages/otr-core/src/db/index.ts
Labels: size/XXL

#527 fix: search sorting
  apps/web/app/server/oRPC/procedures/searchProcedures.ts
Labels: size/XS
