Repository osu-tournament-rating/otr-web, pull requests merged in 2025-10, with the labels that each got.

#529 fix: leaderboard filter ui glitch
  apps/web/components/leaderboard/LeaderboardFilter.tsx
Labels: bug, size/M, type:ui/ux

#530 fix: leaderboard 'Rank' column data alignment
  apps/web/app/leaderboard/columns.tsx
Labels: size/XS

#534 Update deployment pipeline to remove unnecessary input
  .github/workflows/deploy-trigger.yml
  .github/workflows/deploy.yml
Labels: size/M

#536 Rename sql functions to use public schema
  apps/web/drizzle/0003_audit_triggers.sql
Labels: size/M

#543 Add light/dark mode styling for admin buttons
  apps/web/app/tournaments/[id]/page.tsx
  apps/web/components/admin-notes/AdminNoteView.tsx
  apps/web/components/games/GameCardHeader.tsx
  apps/web/components/matches/MatchCard.tsx
  apps/web/components/tournaments/TournamentAdminView.tsx
Labels: bug, size/M

#540 Add "Pooled Beatmaps" card to player page
  apps/web/app/players/[id]/page.tsx
  apps/web/app/server/oRPC/procedures/playerProcedures.ts
  apps/web/app/server/oRPC/router.ts
  apps/web/components/games/BeatmapBackground.tsx
  apps/web/components/icons/ModIconset.tsx
  apps/web/components/player/PlayerBeatmapCard.tsx
  apps/web/components/player/PlayerBeatmapTournamentTable.tsx
  apps/web/components/player/PlayerBeatmapsList.tsx
  apps/web/lib/orpc/queries/playerBeatmaps.ts
  apps/web/lib/orpc/schema/playerBeatmaps.ts
  apps/web/lib/utils/date.ts
  packages/otr-core/src/index.ts
  packages/otr-core/src/utils/time.ts
Labels: size/XXL, feature

#549 Make tournament card more compact, change default shown 3->5
  apps/web/components/player/PlayerTournamentCard.tsx
  apps/web/components/player/PlayerTournamentsList.tsx
Labels: size/M

#551 Score progression chart now filters for verified games
  apps/web/components/matches/MatchScoreGapChart.tsx
  apps/web/components/matches/MatchTeamScoresChart.tsx
Labels: size/L

#553 Add docs button + formatting
  apps/web/app/players/[id]/page.tsx
  apps/web/app/server/oRPC/procedures/playerProcedures.ts
  apps/web/components/buttons/DocsButton.tsx
  apps/web/components/header/Header.tsx
  apps/web/components/player/PlayerBeatmapsList.tsx
  apps/web/lib/orpc/schema/playerBeatmaps.ts
Labels: size/M, pr:feature

#558 Sync friends on login
  apps/web/drizzle/0004_nifty_prism.sql
  apps/web/drizzle/meta/0004_snapshot.json
  apps/web/drizzle/meta/_journal.json
  apps/web/lib/auth/auth.ts
  packages/otr-core/src/db/relations.ts
  packages/otr-core/src/db/schema.ts
Labels: size/XXL, pr:feature

#560 Filter bots more accurately when syncing friends
  apps/web/lib/auth/auth.ts
Labels: size/S

#557 Make tournament/beatmap cards more compact
  apps/web/components/player/PlayerBeatmapCard.tsx
  apps/web/components/player/PlayerTournamentCard.tsx
  apps/web/components/tournaments/TournamentCard.tsx
  apps/web/components/tournaments/list/TournamentList.tsx
Labels: size/M

#555 Pass default ruleset into getTournaments() correctly
  apps/web/app/players/[id]/page.tsx
Labels: pr:bug, size/XS

#559 Search improvements
  apps/web/app/server/oRPC/procedures/searchProcedures.ts
  apps/web/drizzle/0005_mature_rafael_vega.sql
  apps/web/drizzle/meta/0005_snapshot.json
  apps/web/drizzle/meta/_journal.json
  apps/web/lib/orpc/schema/base.ts
  apps/web/lib/utils/search.tsx
  packages/otr-core/src/db/schema.ts
Labels: size/XXL

#562 Clear warnings upon verification/rejection
  apps/web/app/server/oRPC/procedures/games/adminProcedures.ts
  apps/web/app/server/oRPC/procedures/matches/adminProcedures.ts
  apps/web/app/server/oRPC/procedures/tournaments/__tests__/tournamentAdminUpdateProcedure.test.ts
  apps/web/app/server/oRPC/procedures/tournaments/adminProcedures.ts
  packages/otr-core/src/db/rejection-cascade.ts
Labels: pr:bug, size/L

#563 Filter pooled beatmaps based on ruleset
  apps/web/app/server/oRPC/procedures/playerProcedures.ts
  apps/web/components/player/PlayerBeatmapsList.tsx
Labels: pr:bug, size/M
