Repository osu-tournament-rating/otr-web, pull requests merged in 2025-03, with the labels that each got.

#270 Matches scores style fix
  components/Enums/Enums.module.css
  components/Enums/ModsDisplay/ModsDisplay.tsx
  components/Enums/RejectionReason.tsx
  components/Games/AdminView/GameAdminView.module.css
  components/Games/AdminView/GameAdminView.tsx
  components/Games/List/ListItem/GamesListItem.module.css
  components/Games/List/ListItem/GamesListItemFooter.tsx
  components/Modal/Modal.module.css
  components/Scores/GameScore.module.css
  components/Scores/GameScore.tsx
Labels: size/L

#275 Bump next to 15.2.3
  package-lock.json
  package.json
Labels: size/XS

#273 Add leaderboard page with filter support
  .github/CODEOWNERS
  .gitignore
  app/globals.css
  app/leaderboard/columns.tsx
  app/leaderboard/data-table.tsx
  app/leaderboard/page.tsx
  app/tournaments/[id]/data-table.tsx
  app/tournaments/[id]/page.tsx
  components/admin-notes/AdminNoteForm.tsx
  components/games/GameAdminView.tsx
  components/icons/TierIcon.tsx
  components/leaderboard/LeaderboardFilter.tsx
  components/select/multiple-select.tsx
  components/ui/pagination.tsx
  components/ui/slider.tsx
  components/ui/toggle-group.tsx
  components/ui/toggle.tsx
  lib/actions/leaderboard.ts
  lib/api.ts
  lib/schema.ts
  lib/utils/leaderboard.ts
  lib/utils/urlParams.ts
  package-lock.json
  package.json
  public/icons/tiers/Bronze I.svg
  public/icons/tiers/Bronze II.svg
  public/icons/tiers/Bronze III.svg
  public/icons/tiers/Diamond I.svg
  public/icons/tiers/Diamond II.svg
  public/icons/tiers/Diamond III.svg
  public/icons/tiers/Elite Grandmaster-Old.svg
  public/icons/tiers/Elite Grandmaster.svg
  public/icons/tiers/Emerald I.svg
  public/icons/tiers/Emerald II.svg
  public/icons/tiers/Emerald III.svg
  public/icons/tiers/Gold I.svg
  public/icons/tiers/Gold II.svg
  public/icons/tiers/Gold III.svg
  public/icons/tiers/Grandmaster I.svg
  public/icons/tiers/Grandmaster II.svg
  public/icons/tiers/Grandmaster III.svg
  public/icons/tiers/Master I.svg
  public/icons/tiers/Master II.svg
  public/icons/tiers/Master III.svg
  public/icons/tiers/Platinum I.svg
  public/icons/tiers/Platinum II.svg
  public/icons/tiers/Platinum III.svg
  public/icons/tiers/Silver I.svg
  public/icons/tiers/Silver II.svg
  public/icons/tiers/Silver III.svg
Labels: type:feature, size/XXL

#278 Fix newlines in match warning tooltip
  components/badges/WarningFlagsBadge.tsx
Labels: size/S

#280 Center global rank and player username on the leaderboard vertically
  app/leaderboard/columns.tsx
Labels: size/XS

#283 Keep user values on filter reset
  components/leaderboard/LeaderboardFilter.tsx
Labels: size/XS

#285 Rearrange boolean expression for submit button checks
  components/admin-notes/AdminNoteForm.tsx
  components/games/GameAdminView.tsx
  components/matches/MatchAdminView.tsx
  components/tournaments/TournamentAdminView.tsx
Labels: size/S
